#!/usr/bin/env bash
# Deploys the website to preview or production.
# ---------------------------------------------

read local_ref local_sha remote_ref remote_sha
TEMP="$HOME/.tmp-aedifico/"
REPO="$PWD"

if [ $remote_ref = 'refs/heads/master' ]; then
    TARGET="$PWD/../"
    BRANCH="master"
    SERVICE="aedifico.service"
elif [ $remote_ref = 'refs/heads/preview' ]; then
    TARGET="$PWD/../preview/"
    if [ ! -d $TARGET ]; then
        mkdir $TARGET
    fi
    BRANCH="preview"
    SERVICE="aedifico-preview.service"
else
    printf "\nCommit to unkwnow branch, nothing to do!\n. . . \n"
    exit
fi

if [ -d $TEMP ]; then
    rm -R $TEMP
fi

printf "Creating a temporary directory ...\n\n"
mkdir $TEMP

printf "Checking out branch $BRANCH\n\n"
git --work-tree=$TEMP --git-dir=$REPO checkout -f $BRANCH

printf "Using temporary directory\n\n"
cd $TEMP

printf "Checking for existing folders:\n\n"
for SUB in `ls -d */`; do
    TEST=$TARGET$SUB

    if [ -d $TEST ]; then
        printf " - Removing $TEST\n"
        rm -R $TEST
    fi
done

printf "Copying new files ...\n"
cp -r ./* $TARGET

printf "Restarting services\n"
sudo systemctl restart $SERVICE

printf "\n . . . Done!\n"